from ipo_india.ipo_scraper import TopShareBrokersIPO
cls = TopShareBrokersIPO
TopShareBrokersIPO._get_ipos_with_subscription()
TopShareBrokersIPO._TopShareBrokersIPO__get_report_data_table(TopShareBrokersIPO.SUBSCRIPTION_URL)